### ISSUE TITLE
Mitos shouldn't have hard MPI dependency

### ISSUE THREAD

**Issue by daboehme** [LLNL/Mitos#2]
Apparently MPI is only used in the MPI example, not the library itself, which hardly justifies making MPI a required dependency.

**Comment by alfredo-gimenez** [comment]
In the develop branch, the library hooks include MPI hooks: https://github.com/LLNL/Mitos/blob/develop/src/mitoshooks.h#L16

This could be decoupled however, in the sense that the hooks not be compiled if MPI is not found through cmake.

**Comment by alfredo-gimenez** [comment]
Fixed with 576762e
